sudo: required

os:
  - windows
## Just testing windows for now...
##  -linux

language: shell

before_install:
  - |
    env | sort
    export DOCKER_ROOT=microsoft/windowsservercore:1803
    export REPO_MNT=/c/repo

# Perform docker image setup, which sets up the environments
install:
  - |
    # - - Setup some docker images as Haxe+hxcpp build environments - -

    # Neko 2.1.0 base image
    echo "BEFORE"
    echo "docker run -v C:\Users\travis\build\jcward\hxtelemetry:C:\repo\ $DOCKER_ROOT c:\cygwin\bin\bash -c \"dir; cd /c/repo; dir\""
    docker run -v C:\Users\travis\build\jcward\hxtelemetry:C:\repo\ $DOCKER_ROOT c:\cygwin\bin\bash -c "dir; cd /c/repo; dir"
    echo "AFTER"
    (docker commit `docker ps -lq` | cut -c8-) > ~/.docker.image.neko
    echo "AFTER COMMIT"
    date
    echo "Write base neko image `cat ~/.docker.image.neko`"

script:
    date
