sudo: required

os:
  - windows
  - linux

language: shell

before_install:
  - |
    echo "ok"

# Perform docker image setup, which sets up the environments
install:
  - |
    echo "ok"

script:
  - cd $TRAVIS_BUILD_DIR && ./ci/cygwin_ci.sh
