sudo: required

os:
  - windows
## Just testing windows for now...
##  -linux

language: shell

before_install:
  - |
    env | sort
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get -y install docker-ce
      export DOCKER_ROOT=ubuntu:14.04
    else
      export DOCKER_ROOT=microsoft/windowsservercore:1803
    fi

  # Repo mount location inside docker
  - export REPO_MNT=/repo

# Perform docker image setup, which sets up the environments
install:
  - |
    # - - Setup some docker images as Haxe+hxcpp build environments - -

    set -x

    # Neko 2.1.0 base image
    date
    docker run -e LANG=C.UTF-8 -v "$TRAVIS_BUILD_DIR:$REPO_MNT" $DOCKER_ROOT /bin/bash -c "cd $REPO_MNT; source ci/init_env.source; source ci/setup.neko.source"
    (docker commit `docker ps -lq` | cut -c8-) > ~/.docker.image.neko
    date
    echo "Write base neko image `cat ~/.docker.image.neko`"

script:
    date
