sudo: required

os:
  - windows
## Just testing windows for now...
##  -linux

language: shell

before_install:
  - |
    env | sort
    export DOCKER_ROOT=microsoft/windowsservercore:1803
    export REPO_MNT=/c/repo
    export VOLUMES="-v \"c:\\Users\\travis\\build\\jcward\\hxtelemetry:C:\\repo\""

# Perform docker image setup, which sets up the environments
install:
  - |
    # - - Setup some docker images as Haxe+hxcpp build environments - -

    # Neko 2.1.0 base image
    date
    echo "docker run -e LANG=C.UTF-8 $VOLUMES $DOCKER_ROOT /bin/bash -c \"cd $REPO_MNT; source ci/init_env.source; source ci/setup.neko.source\""
    docker run -e LANG=C.UTF-8 $VOLUMES $DOCKER_ROOT /bin/bash -c "cd $REPO_MNT; source ci/init_env.source; source ci/setup.neko.source"
    (docker commit `docker ps -lq` | cut -c8-) > ~/.docker.image.neko
    date
    echo "Write base neko image `cat ~/.docker.image.neko`"

script:
    date
